### PR TITLE
Bump to scala 2.13.6

### PR DESCRIPTION
**Pull request by arigoldx**

### CODE REVIEW

**Comment by arigoldx** [comment]
@Shadowfiend dunno if you wanna see this but here's the PR to bump, courtesy of Lars :)

After this we'll have to do a push-to-maven huh? Happy to help with that in any way :bow:.

**Review by Shadowfiend — COMMENTED** [review]
Do we need to drop 2.11 support? Fine if yes, just wondering.

**Comment by arigoldx** [comment]
Funny, I brought that up. We discussed but nothing concrete came up. I'll ask Lars again if there's something explicit.

**Comment by lars-n** [comment]
If it compiles sure, let's add back 2.11

**Comment by arigoldx** [comment]
Right-e-o, I went ahead and reverted the 2.12 versioning to use `.9` since that's how it was. Wouldn't wanna break anyone using 2.12.9 tho yah, I wonder how massive that population is.

What's next? 😹

**Comment by Shadowfiend** [comment]
Patch bump should be fine/a good thing. 

I need to see if there's an easy GitHub workflow I can get up here to do the builds...

**Comment by arigoldx** [comment]
> Patch bump should be fine/a good thing.

Well then! How come? I was under the impression that any versioning change _could_ be a breaking versioning change.

'was about to push a commit to bring it back to `2.12.14` but got curious :)

**Comment by arigoldx** [comment]
FYI, gentlemen, I'ma merge this mañana.

At that point I'm happy to help with publishing, and to that end, will start figuring out How To Publish #newbie.

**Comment by Shadowfiend** [comment]
> I was under the impression that any versioning change could be a breaking versioning change.

Strictly speaking yes, but the Scala team commits to not breaking things in patch releases. Sometimes they still do but the follow up is a patch release that unbreaks.

**Comment by arigoldx** [comment]
> the Scala team commits to not breaking things in patch releases. Sometimes they still do but the follow up is a patch release that unbreaks.

well that's kinda lovely ain't it :)

**Comment by arigoldx** [comment]
So again I'm admittedly new to the whole Maven/Ivy/Sonatype artifact publishing racket. I say "Sonatype" 'cause that's where I found the artifacts: https://search.maven.org/search?q=lift-formality

From my [readings](https://medium.com/rahasak/publish-scala-library-project-to-maven-central-with-sonatype-d7edaa67d275) seems like we need an account at Sonatype? Maybe ya have one @Shadowfiend? Maybe ya can add me (or something) so I can save ya the typing & clicking?

//cc @lars-n

**Comment by arigoldx** [comment]
Ah I also see a [GitHub Actions workflow](https://community.axonivy.com/d/156-build-and-deploy-on-github) which, as ya said, might be easier. Still I betcha I need access or summat.

**Comment by Shadowfiend** [comment]
I do have an account and should be able to add you... As soon as I remember how that disaster of a system works 😅

**Comment by Shadowfiend** [comment]
Actually it might be a matter of posting to a sonatype Jira or something like that... Can't remember exactly.

**Pull request merged**
