### PR TITLE
Bump to Scala 2.12.10

### PR DESCRIPTION
**Pull request by Shadowfiend**

### CODE REVIEW

**Comment by arigoldx** [comment]
Happy to help make this PR happen.. especially if we change `2.12.10` to `2.13` :blush:.

(Also :wave:! :D)

**Comment by Shadowfiend** [comment]
We probably need to move this to GitHub actions, though if you want to try to push a commit that adds 2.13 to the matrix to see if it works I'm in 😁

**Comment by arigoldx** [comment]
> We probably need to move this to GitHub actions,

Hrm.. you mean move `continuous-integration/travis-ci/push` to GitHub actions?

Regardless I'll try to futz next week 👷.

**Comment by Shadowfiend** [comment]
Yeah. Travis ci stuff for open source has changed, and I'm not sure I know enough about how.

**Comment by arigoldx** [comment]
Maybe this PR can be closed due to https://github.com/hacklanta/lift-formality/pull/34?

**Pull request closed without merging**
