### PR TITLE
Empty Validation: Allow validating fields that are not sent to the server

### PR DESCRIPTION
**Pull request by Shadowfiend**
Per #6, we have an issue where an empty field can't be marked as invalid
because it never gets a chance to run against validations. To fix this, we:
 - Separate the computation of the final, fully validated value of the field
   into its own method, and cache it in a `TransientRequestVar`.
 - Cache the field name in a `RequestVar` and abstract out the adding of
   a validation error for the field based on this cache.
 - Introduce a new concept, boxed validations, which are validations that
   can take boxes of the field value instead of just the field value.
 - Add overloads for `withValidation` and `?` to be able to add boxed
   validations.
 - Run those validators when computing the final value if there is no seen
   value for the field, allowing the boxed validators to run even if there is
   no submission for the field.

### CODE REVIEW

**Comment by arigoldx** [comment]
I gave the code some :eyes: and didn't see any typos or anything..Would ya like me to do any user testing?

**Comment by arigoldx** [comment]
@Shadowfiend was the plan to merge this? Or was there some other way to get it in sos I can use it?

**Comment by arigoldx** [comment]
Just realized.. doesn't this imply a change to `README.md`?

**Comment by Shadowfiend** [comment]
Good pint on the readme. Should probably also update the `notEmpty` validator.

**Comment by arigoldx** [comment]
Looks good t'me! :+1:

**Pull request merged**
